- hosts: tag_Name_Scenario
  name: start geth
  remote_user: "{{ remote_user }}"
  gather_facts: true
  roles:
    - scenario 
    - common
  tags:
    - start_geth

  tasks:
    # Collect instance id: http://stackoverflow.com/a/27307254 
    - action: ec2_facts

    - name: stop geth (KILL)
      shell: "killall -15 geth"

    - name: init geth
      shell:
        cmd: "geth --datadir {{ geth_datadir }} init {{ geth_datadir }}/genesis.json"

      # run geth in background and redirect output to ~/geth.log 
    - name: run geth command
      shell:
        cmd: "nohup {{ geth_datadir }}/start.sh 2>&1 {{ user_home }}/geth.log &"


- hosts: tag_Name_Scenario
  name: start raiden
  remote_user: "{{ remote_user }}"
  gather_facts: true
  roles:
    - scenario 
    - common
  tags:
    - start_raiden
  vars:
    scenario_runner: "{{ user_home }}/raiden/tools/app.py"

  tasks:
    # Collect instance id: http://stackoverflow.com/a/27307254 
    - action: ec2_facts

    - name: configured raiden_ports
      find: 
        patterns: "4*"
        paths: "{{ user_home }}"
        file_type: directory
      register: dirs

    - name: set fact for ports
      set_fact:
        raiden_ports: "{{ dirs.files | map(attribute='path') | map('basename') | list }}"

    - name: debug
      debug:
        var: dirs

    - name: debug
      debug:
        var: raiden_ports
      # note: this is far from working for ansible, just to get the general idea
    - name: shell command stub (for dir in {{ user_home }}/40*; do...)
      #chdir: "{{ user_home }}"
      debug: 
        msg: "raidenvenv/bin/raiden $(cat {{ item }}/raiden_flags.txt) --privatekey $(cat {{ item }}/privatekey.txt) --external_listen_address {{ ansible_ec2_local_ipv4 }}:{{ item }}"
      with_items:
        - "{{ raiden_ports }}"
